### ISSUE TITLE
Android 12 BLUETOOTH_CONNECT permission

### ISSUE THREAD

**Issue by dostalleos** [twilio/audioswitch#101]
Could you please add Android 12 support? When targeting Android 12, AudioSwitch causes app to crash, because of missing `BLUETOOTH_CONNECT` permission. Please see stack trace bellow.

I know that I can add this permission myself, but I do not want bother users with this permissions request, just because they might have BT headphones. Is it really necessary to request this permission?

Thank you

```
java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@509fd176: HeadsetService
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at android.bluetooth.IBluetoothHeadset$Stub$Proxy.getConnectedDevicesWithAttribution(IBluetoothHeadset.java:1040)
        at android.bluetooth.BluetoothHeadset.getConnectedDevices(BluetoothHeadset.java:549)
        at com.twilio.audioswitch.bluetooth.BluetoothHeadsetManager.onServiceConnected(BluetoothHeadsetManager.kt:86)
        at android.bluetooth.BluetoothHeadset$3.handleMessage(BluetoothHeadset.java:1422)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by mrea1** [comment]
Checking in - any ETA on this one?

**Comment by afalls-twilio** [comment]
This issue is fixed in the release version 1.1.3.

**Comment by mykola-tarchanyn** [comment]
Looks like `1.1.3` has side effects that will lead to a crash. I filled a separate [ticket](https://github.com/twilio/audioswitch/issues/108) about it. cc @afalls-twilio @4brunu

**Comment by PeterLecky** [comment]
I am using latest version (1.5) in the project which is compiled against lower api and bluetooth crash mentioned in the description of this bug still happens when running on android 12 also in situation when i have  required permission.
